statistics.mongo.host: localhost
statistics.mongo.database: statisticsDev
statistics.hostname: localhost

statistics.timeZone: UTC

spring:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    time-zone: 'UTC'
    serialization:
      write-dates-as-timestamps: false

statistics.api.security:
  accessKeys:
    - key: 'test_read_key'
      secret: 'test_read_auth'
      roles:
        - 'read'
    - key: 'test_write_key'
      secret: 'test_write_auth'
      roles:
        - 'write'